name: Run Test with Makefile

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: make install

      - name: Run check
        run: make check

      - name: Run tests
        run: make test
